### PR TITLE
feat: optional commit-lints

### PR DESCRIPTION
**Pull request by manuel-bertoluzza-zupit**
This PR introduces the option to make "Lint commits" job optional.

In repositories where the "squash and merge" strategy is used for merging pull requests, commits are squashed in every branch after merge.
Linting commits that in `main` are lost after the PR has been merged is not very useful.

The change is backwards compatible, because by default "Lint commits" continues to run as it does currently.

---

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] Does the code follow the team's coding standards and best practices?
- [x] Is the code well-organized and easy to understand?
- [x] Are file, variable and function names clear and meaningful?
- [x] Are there any duplicated code blocks that can be refactored into reusable functions?

## Functionality
- [x] Does the PR implement the intended functionality or fix the issue described in the title and description?
- [x] Are there any edge cases that have been overlooked?

## Testing
- [x] Are there sufficient tests covering the changes?
- [x] Are there any missing test cases that need to be added?
- [x] Has the code been tested in different environments if applicable (e.g., browsers, platforms, devices)?

## Documentation
- [x] Are the changes well-documented and easy to understand?
- [x] Are there any missing or outdated comments in the code?
- [x] Is the PR title clear and detailed enough to provide necessary context?

## Performance
- [x] Do the changes have any impact on the system's performance?
- [x] Are there any potential bottlenecks that need to be addressed?

## Dependencies
- [x] Have the changes introduced any new dependencies or updated existing ones?
- [x] Are the dependencies up-to-date and secure?

## Compatibility
- [x] Will the changes have any adverse effects on other parts of the system?
- [x] Do they work well with other existing features?

## Continuous Integration/Deployment (CI/CD)
- [x] Have the changes passed the CI/CD pipeline?
- [x] Are there any deployment considerations or steps that need to be taken into account?

## Code Review language
- [x] Is the feedback provided in a constructive and respectful manner?
- [x] Has the reviewer avoided personal attacks or harsh language?
- [x] Are there any suggestions for improvement or alternative approaches?

### CODE REVIEW

**Comment by alessio-libardi-zupit** [comment]
I'm sad I wasn't tagged here. My honest opinion is that we should just remove the job.

> Linting commits that in main are lost after the PR has been merged is not very useful.

Indeed that's useless, so why not just removing the job instead of adding complexity with a flag?

**Comment by omar-muscatello-zupit** [comment]
We agree with @alessio-libardi-zupit to remove the both the job itself. @manuel-bertoluzza-zupit would you mind updating your code?

**Comment by manuel-bertoluzza-zupit** [comment]
I removed `lint-commits` job as requested

**Pull request merged**
